#!/bin/bash

sudo pacman -S ttf-hack-nerd ttf-font-awesome \
	neovim mpd mpc ncmpcpp xclip pipewire-media-session \
	pipewire-pulse

# bash
if ! [ -L "$HOME/.bashrc" ]; 
then
  ln -sf "$PWD/bash/.bashrc" $HOME
else
  echo "bashrc symlink already exists"
fi

if ! [ -L "$HOME/.bash_profile" ];
then
  ln -sf "$PWD/bash/.bash_profile" $HOME
  source "$HOME/.bash_profile"
else
  echo "bash_profile symlink already exists"
fi

# nvim
if ! [ -L "$XDG_CONFIG_HOME/nvim" ]; 
then
  ln -s  "$PWD/nvim" $XDG_CONFIG_HOME
else
  echo "nvim symlink already exists"
fi

# mpd
if ! [ -L "$XDG_CONFIG_HOME/mpd" ];
then
  ln -s "$PWD/mpd" $XDG_CONFIG_HOME
else
  echo "mpd symlink already exists"
fi

# ncmpcpp
if ! [ -L "$XDG_CONFIG_HOME/ncmpcpp" ];
then
  ln -s "$PWD/ncmpcpp" $XDG_CONFIG_HOME
else
  echo "ncmpcpp symlink already exists"
fi

#vieb
if ! [ -L "$XDG_CONFIG_HOME/viebrc" ]; 
then
  ln -s "$PWD/vieb/viebrc" $XDG_CONFIG_HOME
else
  echo "viebrc symlink already exists"
fi

#user scripts
if ! [ -L "$XDG_DATA_HOME/bin" ];
then
  ln -s "$PWD/bin" $XDG_DATA_HOME
else
  echo "bin symlink already exists"
fi
